# Site
repository: 100sun/100sun.github.io
favicon: images/my_favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sun Hye Baek
title: Studying Computer Science/Engineering, Keen on Cloud/Bigdata
email: sunhyebaek1@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username: 100sun
facebook_username: sunhye.baek.14
# instagram_username: _100sun_
linkedin_username: sun-hye-baek-765220166
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: naverblog
#   icon: fas fa-globe
#   url: https://blog.naver.com/92tjsgp14 
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_profile_image: images/my_profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Sophia and I'm studying computer science. I'm interested in <mark>Cloud, and Big Data</mark>. 
  I'd love to learn new solutions. I have experience as a back-end developer.
  I am most skilled in: <mark>AWS</mark> and <mark>Python</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Megazone Cloud
        link: https://www.megazone.com/us/
        # link_text: boringtitle.com
        additional_links:
          - title:  SpaceOne
            icon: fab fa-globe
            url: https://www.spaceone.org/
        sub_title: Backend Devloper
        caption: Jan 2021 – Mar 2021
        quote: >
          SpaceONE is an Open-Source Platform and Enables Integrated Management of Multi-Cloud.
        description: | # this will include new lines to allow paragraphs
          Developed plugins to collect user data in the various cloud services using AWS boto3 API and Alibaba Cloud Python SDK for the marketplace of SpaceONE.
      - layout: left
        title: DataPower
        link: https://www.datapower.company/
        # link_text: boringtitle.com
        additional_links:
          - title:  SpaceOne
            icon: fab fa-globe
            url: https://www.spaceone.org/
        sub_title: Backend Devloper
        caption: Jan 2021 – Mar 2021
        quote: >
          Datapoweris Data Integration consulting company.
        description: | # this will include new lines to allow paragraphs
          Built a company’s website by GatsbyJS.
          Made and operated their partner’s official blogs – Equalum, Wandisco.
          Configured test server (Helm Chart etc) and Equalum servers as a technical engineer.
          Contributed in the project to migrate faster for KOBIC as a technical interpreter in the whole progress resulting in reducing migration time from few days to few hours.
          Translated a number of documents related to data infrastructure solutions.
      - layout: left
        title: Global Knowledge
        link: https://www.globalknowledge.com 
        # link_text: boringtitle.com
        additional_links:
          - title:  SpaceOne
            icon: fab fa-globe
            url: https://www.spaceone.org/
        sub_title: Backend Devloper
        caption: Jan 2021 – Mar 2021
        quote: >
          Instructed the employees of SK C&C as an assistant for the cloud education.
        description: | # this will include new lines to allow paragraphs
          Instructed Terraform, Docker, Kubernetes, AWS Cloud Services, Azure Cloud services, and the cloud Infrastructure as an assistant.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Scholarship Chatbot
        link: https://pf.kakao.com/_xgxjxaPK
        link_text: Find your customized scholarships by answering simple questions!
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Scholarship Chatbot is a service that users can easily get a recommendation for their personalized scholarships in South Korea. You can try this service on the best messenger platform, Kakaotalk.
          This got over 7,000 users in one week after release and went out on the online news of a university in Korea.
        description: | # this will include new lines to allow paragraphs
          As a backend developer, 
          •	In responsible for provisioning infrastructure–AWS EC2, MongoDB, Docker, Kubernetes.
          •	Developed scholarship recommendation service and refined the response data from web crawling, user and updated database in Python.
          •	Automated the deployment and repetitive jobs using Github Action, Nohup.
          •	Developed a Flask application to communicate with the Kakaotalk Open Builder.

      - layout: top-middle
        title: InventoryBox
        additional_links:
          - title:  InventoryBox/InventoryBox_Server
            icon: fab fa-github
            url: github.com/InventoryBox/InventoryBox_Server
        quote: >
          Inventory management application for individual restaurant operators
        description: | # this will include new lines to allow paragraphs
          As a back-end developer, I designed the database with oracle sql and built "inventory tracking" and "inventory exchange" capabilities based on the cloud using AWS EC2 and S3. 
          I learned cooperation through GitHub through collaboration with two other back-end developers, and also through collaboration with six front-end and three designers, I learned the project flow.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Seoul Sungshin Women University
        caption: 2018 - 2022
        sub_title: BSc Computer Science / Computer Engineer
        description: | # this will include new lines to allow paragraphs
          During my time at SSWU I learnt most of my key skills and base knowledgement. I thouroughly enjoyed my time as university. 
          I spent a lot of my free time as a committee member of the *Information System Engineering Club* teaching the juniors.

      - layout: left
        title: California State University, Fullerton
        caption: 2019
        sub_title: BSc Computer Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at CSUF I learnt using open-source software and their programming style. I experienced different cultures and diversity in California. So I could make a global mindset and teamwork. 
          I spent a lot of my free time as a member of the *CSUF Adventure Club* and learnt a healthy work life balance.

      - layout: left
        title: Seoul Paekam Highschool
        caption: 2016 - 2018
        sub_title: Science
        description: | # this will include new lines to allow paragraphs
          During my time at Paekam I learnt Python Language and wrote an R&E(Research & Experiment) essay about *Our Countermeasures for the Big Data Era* using Hadoop and Nifi. 
          I spent a lot of my free time as a member of the *PaekAm Science Club* experimenting with interesting science.



  - title: Organizations
    layout: list # Type of content section (list/text)
    content:
      # - layout: left
      #   title: Seoul Sungshin Women University
      #   caption: 2018 - 2022
      #   sub_title: BSc Computer Science / Computer Engineer
      #   description: | # this will include new lines to allow paragraphs
      #     During my time at SSWU I learnt most of my key skills and base knowledgement. I thouroughly enjoyed my time as university. 
      #     I spent a lot of my free time as a committee member of the *Information System Engineering Club* teaching the juniors.
    
      - layout: left
        title: SOPT
        jobs:
          - title: 26 Server Part
            caption: March 2020 - August 2020
            link: https://github.com/our-sopt-server-team7/100sun
          - title: 23 Server Part
            caption: August 2018 - Feburary 2019
            link: https://github.com/100sun/SOPT-23-Server
        # caption:
        sub_title: >
          The biggest IT venture club between university student
        description: | # this will include new lines to allow paragraphs
          Deploy Server using Node.js & Spring Boot Framework, Experience the entire process of in charge of the backend in the project, Supporters of Global Leaders Forum, Planning their 10th anniversary conference

      - layout: left
        title: TIPS
        caption: June 2018 - August 2018
        link: https://blog.naver.com/92tjsgp14 
        link_text: Notes of the course on Naver Blog
        description: | # this will include new lines to allow paragraphs
          Learn C/MFC/Socket from a Microsoft MVP (2012-) in Microsft Korea

      - layout: left
        title: COMMA
        caption: March 2018 - August 2019
        sub_title: >
          Information System Enginnering club in SSWU
        description: | # this will include new lines to allow paragraphs
          Teaching the juniors and launching some projects with their members

    # layout: text
    # content: | # this will include new lines to allow paragraphs
    #   Alongside my interests in networks and software engineering some of my other interests and hobbies are:
    #   - Rock climbing
    #   - Gaming
    #   - Knitting
    #   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

    #   Look at this cool image  
    #   ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
