# Site
repository: sproogen/resume-theme
favicon: images/my_favico.ico

# Personal info
name: Sun Hye Baek
title: Studying Computer Science/Engineering, Keen on Cloud/Bigdata
email: sunhyebaek99@gmail.com

darkmode : true

# Social links
github_username: 100sun
facebook_username: sunhye.baek.14
instagram_username: _100sun_
linkedin_username: sun-hye-baek-765220166

additional_links:
- title: naverblog
  icon: /images/blog.png
  url: https://blog.naver.com/92tjsgp14

# About Section
# about_title: About Me
about_profile_image: images/my_profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Sun Hye Baek and I'm studying computer science. I'm interesting in AI, Blockchain, <mark>Cloud</mark>, and <mark>Big Data</mark>. 
  I'd love to learn new solutions. I have experience managing server and making software, mobile applications, webpage.
  I am studying [<mark>Algorithm</mark>](https://github.com/100sun/algorithm_in_c) and working at Datapower
#  I am most skilled in: <mark>Programming</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering some of my other interests and hobbies are:
   - Surfing
   - Rick and Morty
   - Pop Rock
   - Fashion
   
# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]